### ISSUE TITLE
Login when the request is blocked behind a corporate proxy / message when offline

### ISSUE THREAD

**Issue by julienkermarec** [capawesome-team/cli#12]
When i have tried today to login with a token (on this example is xxx but with a valid token) and i have received an error message "Invalid token".

After changed from the corporate network to my phone network, the login is successfull.

<img width="565" alt="Capture d’écran 2024-10-10 à 17 30 50" src="https://github.com/user-attachments/assets/055000da-a6e2-4c7f-b9fe-74130bd2a5d1">

Is it possible technically to detect a blocked request for some reason (and not password incorrect automatically ?)

I have tested without connection (in offline) and i have the same message invalid token, and a http-client javascript error :

<img width="567" alt="Capture d’écran 2024-10-10 à 17 36 47" src="https://github.com/user-attachments/assets/f29ae143-08f6-42a2-9a39-c71ee7626803">

**Comment by robingenz** [comment]
Thank you for reporting that! I will fix this in #13. However, I was not able to test the scenario with the corporate firewall. If you would like, you are welcome to test this at your site and create a PR.

**Comment by julienkermarec** [comment]
Tested the #13 and it seems fixed 👍 

<img width="326" alt="Capture d’écran 2024-10-11 à 11 00 50" src="https://github.com/user-attachments/assets/e5b21185-a16c-4e64-8017-35d6019a2d3f">
