### ISSUE TITLE
allow dependency upgrades

### ISSUE THREAD

**Issue by tgabi333** [capawesome-team/cli#15]
Please use at least ^ dependencies in package.json. In our project we use this cli tool and this is the result

![Screenshot 2024-10-24 at 13 28 06](https://github.com/user-attachments/assets/29baecf3-1298-4f01-9be2-cb1f18dbff05)

**Comment by robingenz** [comment]
Thank you for reaching out! I will think about this. Choosing fixed versions was intentional at the time. For now, I will update all dependencies to fix your problem.

**Comment by tgabi333** [comment]
Thank you for your swift reaction @robingenz !
